# Should only run when file changes are made to drive system
name: Drive CI

on:
  push:
    paths:
      - "subsystem-drive/**"
    branches: [main]
  pull_request:
    paths:
      - "subsystem-drive/**"
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cloning SJSU-Dev2
        run: git clone https://github.com/SJSU-Dev2/SJSU-Dev2.git

      - name: Setting up sjsu-dev2 🤖
        run: |
          cd SJSU-Dev2/
          ./setup
          cd ..

      - name: Testing drive system 🦿
        run: |
          cd subsystem-drive/
          make test
